// JavaScript Obfuscator 配置
module.exports = {
  compact: true,
  controlFlowFlattening: true,
  controlFlowFlatteningThreshold: ["0.75"],
  deadCodeInjection: true,
  deadCodeInjectionThreshold: ["0.4"],
  debugProtection: true,
  debugProtectionInterval: ["0.5"],
  disableConsoleOutput: true,
  identifierNamesGenerator: 'hexadecimal',
  log: false,
  numbersToExpressions: true,
  renameGlobals: false,
  selfDefending: true,
  simplify: true,
  splitStrings: true,
  splitStringsChunkLength: ["10"],
  stringArray: true,
  stringArrayEncoding: ["base64"],
  stringArrayIndexShift: true,
  stringArrayWrappersCount: ["2"],
  stringArrayWrappersChainedCalls: true,
  stringArrayWrappersParametersMaxCount: ["4"],
  stringArrayWrappersType: "function",
  stringArrayThreshold: ["0.75"],
  transformObjectKeys: true,
  unicodeEscapeSequence: false
};